debug: true
server:
  port: 8084
spring:
  main:
    web:
      environment: false
  data:
    mongodb:
      uri: mongodb://192.168.1.1:27017
      database: springboot-moquette-dev
service:
    message: Hello World from Api
